# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetPostureNamoUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1127, 751)
        self.verticalLayoutWidget_7 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(570, 70, 531, 205))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.setHAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.setHAll_pushButton.setObjectName(_fromUtf8("setHAll_pushButton"))
        self.horizontalLayout_26.addWidget(self.setHAll_pushButton)
        self.getHAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.getHAll_pushButton.setObjectName(_fromUtf8("getHAll_pushButton"))
        self.horizontalLayout_26.addWidget(self.getHAll_pushButton)
        self.disTHAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.disTHAll_pushButton.setObjectName(_fromUtf8("disTHAll_pushButton"))
        self.horizontalLayout_26.addWidget(self.disTHAll_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.ID21_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.ID21_label.setObjectName(_fromUtf8("ID21_label"))
        self.horizontalLayout_20.addWidget(self.ID21_label)
        self.motorType21_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motorType21_label.setObjectName(_fromUtf8("motorType21_label"))
        self.horizontalLayout_20.addWidget(self.motorType21_label)
        self.motor21center_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motor21center_label.setObjectName(_fromUtf8("motor21center_label"))
        self.horizontalLayout_20.addWidget(self.motor21center_label)
        self.motor21Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_7)
        self.motor21Value_spinBox.setMaximum(1023)
        self.motor21Value_spinBox.setObjectName(_fromUtf8("motor21Value_spinBox"))
        self.horizontalLayout_20.addWidget(self.motor21Value_spinBox)
        self.motor21value_dial = QtGui.QDial(self.verticalLayoutWidget_7)
        self.motor21value_dial.setMaximum(1023)
        self.motor21value_dial.setObjectName(_fromUtf8("motor21value_dial"))
        self.horizontalLayout_20.addWidget(self.motor21value_dial)
        self.motor21Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor21Set_pushButton.setObjectName(_fromUtf8("motor21Set_pushButton"))
        self.horizontalLayout_20.addWidget(self.motor21Set_pushButton)
        self.motor21Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor21Get_pushButton.setObjectName(_fromUtf8("motor21Get_pushButton"))
        self.horizontalLayout_20.addWidget(self.motor21Get_pushButton)
        self.motor21DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor21DisT_pushButton.setObjectName(_fromUtf8("motor21DisT_pushButton"))
        self.horizontalLayout_20.addWidget(self.motor21DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.ID22_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.ID22_label.setObjectName(_fromUtf8("ID22_label"))
        self.horizontalLayout_21.addWidget(self.ID22_label)
        self.motorType22_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motorType22_label.setObjectName(_fromUtf8("motorType22_label"))
        self.horizontalLayout_21.addWidget(self.motorType22_label)
        self.motor22center_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motor22center_label.setObjectName(_fromUtf8("motor22center_label"))
        self.horizontalLayout_21.addWidget(self.motor22center_label)
        self.motor22Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_7)
        self.motor22Value_spinBox.setMaximum(1023)
        self.motor22Value_spinBox.setObjectName(_fromUtf8("motor22Value_spinBox"))
        self.horizontalLayout_21.addWidget(self.motor22Value_spinBox)
        self.motor22value_dial = QtGui.QDial(self.verticalLayoutWidget_7)
        self.motor22value_dial.setMaximum(1023)
        self.motor22value_dial.setObjectName(_fromUtf8("motor22value_dial"))
        self.horizontalLayout_21.addWidget(self.motor22value_dial)
        self.motor22Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor22Set_pushButton.setObjectName(_fromUtf8("motor22Set_pushButton"))
        self.horizontalLayout_21.addWidget(self.motor22Set_pushButton)
        self.motor22Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor22Get_pushButton.setObjectName(_fromUtf8("motor22Get_pushButton"))
        self.horizontalLayout_21.addWidget(self.motor22Get_pushButton)
        self.motor22DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor22DisT_pushButton.setObjectName(_fromUtf8("motor22DisT_pushButton"))
        self.horizontalLayout_21.addWidget(self.motor22DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.ID23_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.ID23_label.setObjectName(_fromUtf8("ID23_label"))
        self.horizontalLayout_19.addWidget(self.ID23_label)
        self.motorType23_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motorType23_label.setObjectName(_fromUtf8("motorType23_label"))
        self.horizontalLayout_19.addWidget(self.motorType23_label)
        self.motor23center_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motor23center_label.setObjectName(_fromUtf8("motor23center_label"))
        self.horizontalLayout_19.addWidget(self.motor23center_label)
        self.motor23Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_7)
        self.motor23Value_spinBox.setMaximum(1023)
        self.motor23Value_spinBox.setObjectName(_fromUtf8("motor23Value_spinBox"))
        self.horizontalLayout_19.addWidget(self.motor23Value_spinBox)
        self.motor23value_dial = QtGui.QDial(self.verticalLayoutWidget_7)
        self.motor23value_dial.setMaximum(1023)
        self.motor23value_dial.setObjectName(_fromUtf8("motor23value_dial"))
        self.horizontalLayout_19.addWidget(self.motor23value_dial)
        self.motor23Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor23Set_pushButton.setObjectName(_fromUtf8("motor23Set_pushButton"))
        self.horizontalLayout_19.addWidget(self.motor23Set_pushButton)
        self.motor23Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor23Get_pushButton.setObjectName(_fromUtf8("motor23Get_pushButton"))
        self.horizontalLayout_19.addWidget(self.motor23Get_pushButton)
        self.motor23DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor23DisT_pushButton.setObjectName(_fromUtf8("motor23DisT_pushButton"))
        self.horizontalLayout_19.addWidget(self.motor23DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(570, 280, 531, 451))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.setRAll_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.setRAll_pushButton.setObjectName(_fromUtf8("setRAll_pushButton"))
        self.horizontalLayout_25.addWidget(self.setRAll_pushButton)
        self.getRAll_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.getRAll_pushButton.setObjectName(_fromUtf8("getRAll_pushButton"))
        self.horizontalLayout_25.addWidget(self.getRAll_pushButton)
        self.disTRAll_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.disTRAll_pushButton.setObjectName(_fromUtf8("disTRAll_pushButton"))
        self.horizontalLayout_25.addWidget(self.disTRAll_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.ID11_label = QtGui.QLabel(self.layoutWidget)
        self.ID11_label.setObjectName(_fromUtf8("ID11_label"))
        self.horizontalLayout_12.addWidget(self.ID11_label)
        self.motorType11_label = QtGui.QLabel(self.layoutWidget)
        self.motorType11_label.setObjectName(_fromUtf8("motorType11_label"))
        self.horizontalLayout_12.addWidget(self.motorType11_label)
        self.motor11center_label = QtGui.QLabel(self.layoutWidget)
        self.motor11center_label.setObjectName(_fromUtf8("motor11center_label"))
        self.horizontalLayout_12.addWidget(self.motor11center_label)
        self.motor11Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor11Value_spinBox.setMaximum(4095)
        self.motor11Value_spinBox.setObjectName(_fromUtf8("motor11Value_spinBox"))
        self.horizontalLayout_12.addWidget(self.motor11Value_spinBox)
        self.motor11value_dial = QtGui.QDial(self.layoutWidget)
        self.motor11value_dial.setMaximum(4095)
        self.motor11value_dial.setObjectName(_fromUtf8("motor11value_dial"))
        self.horizontalLayout_12.addWidget(self.motor11value_dial)
        self.motor11Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor11Set_pushButton.setObjectName(_fromUtf8("motor11Set_pushButton"))
        self.horizontalLayout_12.addWidget(self.motor11Set_pushButton)
        self.motor11Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor11Get_pushButton.setObjectName(_fromUtf8("motor11Get_pushButton"))
        self.horizontalLayout_12.addWidget(self.motor11Get_pushButton)
        self.motor11DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor11DisT_pushButton.setObjectName(_fromUtf8("motor11DisT_pushButton"))
        self.horizontalLayout_12.addWidget(self.motor11DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.ID12_label = QtGui.QLabel(self.layoutWidget)
        self.ID12_label.setObjectName(_fromUtf8("ID12_label"))
        self.horizontalLayout_13.addWidget(self.ID12_label)
        self.motorType12_label = QtGui.QLabel(self.layoutWidget)
        self.motorType12_label.setObjectName(_fromUtf8("motorType12_label"))
        self.horizontalLayout_13.addWidget(self.motorType12_label)
        self.motor12center_label = QtGui.QLabel(self.layoutWidget)
        self.motor12center_label.setObjectName(_fromUtf8("motor12center_label"))
        self.horizontalLayout_13.addWidget(self.motor12center_label)
        self.motor12Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor12Value_spinBox.setMaximum(4095)
        self.motor12Value_spinBox.setObjectName(_fromUtf8("motor12Value_spinBox"))
        self.horizontalLayout_13.addWidget(self.motor12Value_spinBox)
        self.motor12value_dial = QtGui.QDial(self.layoutWidget)
        self.motor12value_dial.setMaximum(4095)
        self.motor12value_dial.setObjectName(_fromUtf8("motor12value_dial"))
        self.horizontalLayout_13.addWidget(self.motor12value_dial)
        self.motor12Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor12Set_pushButton.setObjectName(_fromUtf8("motor12Set_pushButton"))
        self.horizontalLayout_13.addWidget(self.motor12Set_pushButton)
        self.motor12Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor12Get_pushButton.setObjectName(_fromUtf8("motor12Get_pushButton"))
        self.horizontalLayout_13.addWidget(self.motor12Get_pushButton)
        self.motor12DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor12DisT_pushButton.setObjectName(_fromUtf8("motor12DisT_pushButton"))
        self.horizontalLayout_13.addWidget(self.motor12DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.ID13_label = QtGui.QLabel(self.layoutWidget)
        self.ID13_label.setObjectName(_fromUtf8("ID13_label"))
        self.horizontalLayout_14.addWidget(self.ID13_label)
        self.motorType13_label = QtGui.QLabel(self.layoutWidget)
        self.motorType13_label.setObjectName(_fromUtf8("motorType13_label"))
        self.horizontalLayout_14.addWidget(self.motorType13_label)
        self.motor13center_label = QtGui.QLabel(self.layoutWidget)
        self.motor13center_label.setObjectName(_fromUtf8("motor13center_label"))
        self.horizontalLayout_14.addWidget(self.motor13center_label)
        self.motor13Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor13Value_spinBox.setMaximum(4095)
        self.motor13Value_spinBox.setObjectName(_fromUtf8("motor13Value_spinBox"))
        self.horizontalLayout_14.addWidget(self.motor13Value_spinBox)
        self.motor13value_dial = QtGui.QDial(self.layoutWidget)
        self.motor13value_dial.setMaximum(4095)
        self.motor13value_dial.setObjectName(_fromUtf8("motor13value_dial"))
        self.horizontalLayout_14.addWidget(self.motor13value_dial)
        self.motor13Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor13Set_pushButton.setObjectName(_fromUtf8("motor13Set_pushButton"))
        self.horizontalLayout_14.addWidget(self.motor13Set_pushButton)
        self.motor13Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor13Get_pushButton.setObjectName(_fromUtf8("motor13Get_pushButton"))
        self.horizontalLayout_14.addWidget(self.motor13Get_pushButton)
        self.motor13DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor13DisT_pushButton.setObjectName(_fromUtf8("motor13DisT_pushButton"))
        self.horizontalLayout_14.addWidget(self.motor13DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.ID14_label = QtGui.QLabel(self.layoutWidget)
        self.ID14_label.setObjectName(_fromUtf8("ID14_label"))
        self.horizontalLayout_15.addWidget(self.ID14_label)
        self.motorType14_label = QtGui.QLabel(self.layoutWidget)
        self.motorType14_label.setObjectName(_fromUtf8("motorType14_label"))
        self.horizontalLayout_15.addWidget(self.motorType14_label)
        self.motor14center_label = QtGui.QLabel(self.layoutWidget)
        self.motor14center_label.setObjectName(_fromUtf8("motor14center_label"))
        self.horizontalLayout_15.addWidget(self.motor14center_label)
        self.motor14Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor14Value_spinBox.setMaximum(4095)
        self.motor14Value_spinBox.setObjectName(_fromUtf8("motor14Value_spinBox"))
        self.horizontalLayout_15.addWidget(self.motor14Value_spinBox)
        self.motor14value_dial = QtGui.QDial(self.layoutWidget)
        self.motor14value_dial.setMaximum(4095)
        self.motor14value_dial.setObjectName(_fromUtf8("motor14value_dial"))
        self.horizontalLayout_15.addWidget(self.motor14value_dial)
        self.motor14Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor14Set_pushButton.setObjectName(_fromUtf8("motor14Set_pushButton"))
        self.horizontalLayout_15.addWidget(self.motor14Set_pushButton)
        self.motor14Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor14Get_pushButton.setObjectName(_fromUtf8("motor14Get_pushButton"))
        self.horizontalLayout_15.addWidget(self.motor14Get_pushButton)
        self.motor14DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor14DisT_pushButton.setObjectName(_fromUtf8("motor14DisT_pushButton"))
        self.horizontalLayout_15.addWidget(self.motor14DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.ID15_label = QtGui.QLabel(self.layoutWidget)
        self.ID15_label.setObjectName(_fromUtf8("ID15_label"))
        self.horizontalLayout_16.addWidget(self.ID15_label)
        self.motorType15_label = QtGui.QLabel(self.layoutWidget)
        self.motorType15_label.setObjectName(_fromUtf8("motorType15_label"))
        self.horizontalLayout_16.addWidget(self.motorType15_label)
        self.motor15center_label = QtGui.QLabel(self.layoutWidget)
        self.motor15center_label.setObjectName(_fromUtf8("motor15center_label"))
        self.horizontalLayout_16.addWidget(self.motor15center_label)
        self.motor15Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor15Value_spinBox.setMaximum(4095)
        self.motor15Value_spinBox.setObjectName(_fromUtf8("motor15Value_spinBox"))
        self.horizontalLayout_16.addWidget(self.motor15Value_spinBox)
        self.motor15value_dial = QtGui.QDial(self.layoutWidget)
        self.motor15value_dial.setMaximum(4095)
        self.motor15value_dial.setObjectName(_fromUtf8("motor15value_dial"))
        self.horizontalLayout_16.addWidget(self.motor15value_dial)
        self.motor15Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor15Set_pushButton.setObjectName(_fromUtf8("motor15Set_pushButton"))
        self.horizontalLayout_16.addWidget(self.motor15Set_pushButton)
        self.motor15Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor15Get_pushButton.setObjectName(_fromUtf8("motor15Get_pushButton"))
        self.horizontalLayout_16.addWidget(self.motor15Get_pushButton)
        self.motor15DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor15DisT_pushButton.setObjectName(_fromUtf8("motor15DisT_pushButton"))
        self.horizontalLayout_16.addWidget(self.motor15DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.ID7_label_ = QtGui.QLabel(self.layoutWidget)
        self.ID7_label_.setObjectName(_fromUtf8("ID7_label_"))
        self.horizontalLayout_17.addWidget(self.ID7_label_)
        self.motorType16_label = QtGui.QLabel(self.layoutWidget)
        self.motorType16_label.setObjectName(_fromUtf8("motorType16_label"))
        self.horizontalLayout_17.addWidget(self.motorType16_label)
        self.motor16center_label = QtGui.QLabel(self.layoutWidget)
        self.motor16center_label.setObjectName(_fromUtf8("motor16center_label"))
        self.horizontalLayout_17.addWidget(self.motor16center_label)
        self.motor16Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor16Value_spinBox.setMaximum(4095)
        self.motor16Value_spinBox.setObjectName(_fromUtf8("motor16Value_spinBox"))
        self.horizontalLayout_17.addWidget(self.motor16Value_spinBox)
        self.motor16value_dial = QtGui.QDial(self.layoutWidget)
        self.motor16value_dial.setMaximum(4095)
        self.motor16value_dial.setObjectName(_fromUtf8("motor16value_dial"))
        self.horizontalLayout_17.addWidget(self.motor16value_dial)
        self.motor16Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor16Set_pushButton.setObjectName(_fromUtf8("motor16Set_pushButton"))
        self.horizontalLayout_17.addWidget(self.motor16Set_pushButton)
        self.motor16Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor16Get_pushButton.setObjectName(_fromUtf8("motor16Get_pushButton"))
        self.horizontalLayout_17.addWidget(self.motor16Get_pushButton)
        self.motor16DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor16DisT_pushButton.setObjectName(_fromUtf8("motor16DisT_pushButton"))
        self.horizontalLayout_17.addWidget(self.motor16DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.ID17_label = QtGui.QLabel(self.layoutWidget)
        self.ID17_label.setObjectName(_fromUtf8("ID17_label"))
        self.horizontalLayout_11.addWidget(self.ID17_label)
        self.motorType17_label = QtGui.QLabel(self.layoutWidget)
        self.motorType17_label.setObjectName(_fromUtf8("motorType17_label"))
        self.horizontalLayout_11.addWidget(self.motorType17_label)
        self.motor17center_label = QtGui.QLabel(self.layoutWidget)
        self.motor17center_label.setObjectName(_fromUtf8("motor17center_label"))
        self.horizontalLayout_11.addWidget(self.motor17center_label)
        self.motor17Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor17Value_spinBox.setMaximum(4095)
        self.motor17Value_spinBox.setObjectName(_fromUtf8("motor17Value_spinBox"))
        self.horizontalLayout_11.addWidget(self.motor17Value_spinBox)
        self.motor17value_dial = QtGui.QDial(self.layoutWidget)
        self.motor17value_dial.setMaximum(4095)
        self.motor17value_dial.setObjectName(_fromUtf8("motor17value_dial"))
        self.horizontalLayout_11.addWidget(self.motor17value_dial)
        self.motor17Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor17Set_pushButton.setObjectName(_fromUtf8("motor17Set_pushButton"))
        self.horizontalLayout_11.addWidget(self.motor17Set_pushButton)
        self.motor17Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor17Get_pushButton.setObjectName(_fromUtf8("motor17Get_pushButton"))
        self.horizontalLayout_11.addWidget(self.motor17Get_pushButton)
        self.motor17DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor17DisT_pushButton.setObjectName(_fromUtf8("motor17DisT_pushButton"))
        self.horizontalLayout_11.addWidget(self.motor17DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 280, 531, 451))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.setLAll_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.setLAll_pushButton.setObjectName(_fromUtf8("setLAll_pushButton"))
        self.horizontalLayout_22.addWidget(self.setLAll_pushButton)
        self.getLAll_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.getLAll_pushButton.setObjectName(_fromUtf8("getLAll_pushButton"))
        self.horizontalLayout_22.addWidget(self.getLAll_pushButton)
        self.disTLAll_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.disTLAll_pushButton.setObjectName(_fromUtf8("disTLAll_pushButton"))
        self.horizontalLayout_22.addWidget(self.disTLAll_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ID1_label = QtGui.QLabel(self.layoutWidget1)
        self.ID1_label.setObjectName(_fromUtf8("ID1_label"))
        self.horizontalLayout_4.addWidget(self.ID1_label)
        self.motorType1_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType1_label.setObjectName(_fromUtf8("motorType1_label"))
        self.horizontalLayout_4.addWidget(self.motorType1_label)
        self.motor1center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor1center_label.setObjectName(_fromUtf8("motor1center_label"))
        self.horizontalLayout_4.addWidget(self.motor1center_label)
        self.motor1Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor1Value_spinBox.setMaximum(4095)
        self.motor1Value_spinBox.setObjectName(_fromUtf8("motor1Value_spinBox"))
        self.horizontalLayout_4.addWidget(self.motor1Value_spinBox)
        self.motor1value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor1value_dial.setMaximum(4095)
        self.motor1value_dial.setObjectName(_fromUtf8("motor1value_dial"))
        self.horizontalLayout_4.addWidget(self.motor1value_dial)
        self.motor1Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor1Set_pushButton.setObjectName(_fromUtf8("motor1Set_pushButton"))
        self.horizontalLayout_4.addWidget(self.motor1Set_pushButton)
        self.motor1Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor1Get_pushButton.setObjectName(_fromUtf8("motor1Get_pushButton"))
        self.horizontalLayout_4.addWidget(self.motor1Get_pushButton)
        self.motor1DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor1DisT_pushButton.setObjectName(_fromUtf8("motor1DisT_pushButton"))
        self.horizontalLayout_4.addWidget(self.motor1DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ID2_label = QtGui.QLabel(self.layoutWidget1)
        self.ID2_label.setObjectName(_fromUtf8("ID2_label"))
        self.horizontalLayout_5.addWidget(self.ID2_label)
        self.motorType2_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType2_label.setObjectName(_fromUtf8("motorType2_label"))
        self.horizontalLayout_5.addWidget(self.motorType2_label)
        self.motor2center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor2center_label.setObjectName(_fromUtf8("motor2center_label"))
        self.horizontalLayout_5.addWidget(self.motor2center_label)
        self.motor2Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor2Value_spinBox.setMaximum(4095)
        self.motor2Value_spinBox.setObjectName(_fromUtf8("motor2Value_spinBox"))
        self.horizontalLayout_5.addWidget(self.motor2Value_spinBox)
        self.motor2value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor2value_dial.setMaximum(4095)
        self.motor2value_dial.setObjectName(_fromUtf8("motor2value_dial"))
        self.horizontalLayout_5.addWidget(self.motor2value_dial)
        self.motor2Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor2Set_pushButton.setObjectName(_fromUtf8("motor2Set_pushButton"))
        self.horizontalLayout_5.addWidget(self.motor2Set_pushButton)
        self.motor2Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor2Get_pushButton.setObjectName(_fromUtf8("motor2Get_pushButton"))
        self.horizontalLayout_5.addWidget(self.motor2Get_pushButton)
        self.motor2DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor2DisT_pushButton.setObjectName(_fromUtf8("motor2DisT_pushButton"))
        self.horizontalLayout_5.addWidget(self.motor2DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ID3_label = QtGui.QLabel(self.layoutWidget1)
        self.ID3_label.setObjectName(_fromUtf8("ID3_label"))
        self.horizontalLayout_6.addWidget(self.ID3_label)
        self.motorType3_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType3_label.setObjectName(_fromUtf8("motorType3_label"))
        self.horizontalLayout_6.addWidget(self.motorType3_label)
        self.motor3center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor3center_label.setObjectName(_fromUtf8("motor3center_label"))
        self.horizontalLayout_6.addWidget(self.motor3center_label)
        self.motor3Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor3Value_spinBox.setMaximum(4095)
        self.motor3Value_spinBox.setObjectName(_fromUtf8("motor3Value_spinBox"))
        self.horizontalLayout_6.addWidget(self.motor3Value_spinBox)
        self.motor3value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor3value_dial.setMaximum(4095)
        self.motor3value_dial.setObjectName(_fromUtf8("motor3value_dial"))
        self.horizontalLayout_6.addWidget(self.motor3value_dial)
        self.motor3Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor3Set_pushButton.setObjectName(_fromUtf8("motor3Set_pushButton"))
        self.horizontalLayout_6.addWidget(self.motor3Set_pushButton)
        self.motor3Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor3Get_pushButton.setObjectName(_fromUtf8("motor3Get_pushButton"))
        self.horizontalLayout_6.addWidget(self.motor3Get_pushButton)
        self.motor3DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor3DisT_pushButton.setObjectName(_fromUtf8("motor3DisT_pushButton"))
        self.horizontalLayout_6.addWidget(self.motor3DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.ID4_label = QtGui.QLabel(self.layoutWidget1)
        self.ID4_label.setObjectName(_fromUtf8("ID4_label"))
        self.horizontalLayout_7.addWidget(self.ID4_label)
        self.motorType4_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType4_label.setObjectName(_fromUtf8("motorType4_label"))
        self.horizontalLayout_7.addWidget(self.motorType4_label)
        self.motor4center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor4center_label.setObjectName(_fromUtf8("motor4center_label"))
        self.horizontalLayout_7.addWidget(self.motor4center_label)
        self.motor4Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor4Value_spinBox.setMaximum(4095)
        self.motor4Value_spinBox.setObjectName(_fromUtf8("motor4Value_spinBox"))
        self.horizontalLayout_7.addWidget(self.motor4Value_spinBox)
        self.motor4value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor4value_dial.setMaximum(4095)
        self.motor4value_dial.setObjectName(_fromUtf8("motor4value_dial"))
        self.horizontalLayout_7.addWidget(self.motor4value_dial)
        self.motor4Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor4Set_pushButton.setObjectName(_fromUtf8("motor4Set_pushButton"))
        self.horizontalLayout_7.addWidget(self.motor4Set_pushButton)
        self.motor4Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor4Get_pushButton.setObjectName(_fromUtf8("motor4Get_pushButton"))
        self.horizontalLayout_7.addWidget(self.motor4Get_pushButton)
        self.motor4DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor4DisT_pushButton.setObjectName(_fromUtf8("motor4DisT_pushButton"))
        self.horizontalLayout_7.addWidget(self.motor4DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ID5_label = QtGui.QLabel(self.layoutWidget1)
        self.ID5_label.setObjectName(_fromUtf8("ID5_label"))
        self.horizontalLayout_8.addWidget(self.ID5_label)
        self.motorType5_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType5_label.setObjectName(_fromUtf8("motorType5_label"))
        self.horizontalLayout_8.addWidget(self.motorType5_label)
        self.motor5center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor5center_label.setObjectName(_fromUtf8("motor5center_label"))
        self.horizontalLayout_8.addWidget(self.motor5center_label)
        self.motor5Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor5Value_spinBox.setMaximum(4095)
        self.motor5Value_spinBox.setObjectName(_fromUtf8("motor5Value_spinBox"))
        self.horizontalLayout_8.addWidget(self.motor5Value_spinBox)
        self.motor5value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor5value_dial.setMaximum(4095)
        self.motor5value_dial.setObjectName(_fromUtf8("motor5value_dial"))
        self.horizontalLayout_8.addWidget(self.motor5value_dial)
        self.motor5Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor5Set_pushButton.setObjectName(_fromUtf8("motor5Set_pushButton"))
        self.horizontalLayout_8.addWidget(self.motor5Set_pushButton)
        self.motor5Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor5Get_pushButton.setObjectName(_fromUtf8("motor5Get_pushButton"))
        self.horizontalLayout_8.addWidget(self.motor5Get_pushButton)
        self.motor5DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor5DisT_pushButton.setObjectName(_fromUtf8("motor5DisT_pushButton"))
        self.horizontalLayout_8.addWidget(self.motor5DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.ID6_label = QtGui.QLabel(self.layoutWidget1)
        self.ID6_label.setObjectName(_fromUtf8("ID6_label"))
        self.horizontalLayout_9.addWidget(self.ID6_label)
        self.motorType6_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType6_label.setObjectName(_fromUtf8("motorType6_label"))
        self.horizontalLayout_9.addWidget(self.motorType6_label)
        self.motor6center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor6center_label.setObjectName(_fromUtf8("motor6center_label"))
        self.horizontalLayout_9.addWidget(self.motor6center_label)
        self.motor6Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor6Value_spinBox.setMaximum(4095)
        self.motor6Value_spinBox.setObjectName(_fromUtf8("motor6Value_spinBox"))
        self.horizontalLayout_9.addWidget(self.motor6Value_spinBox)
        self.motor6value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor6value_dial.setMaximum(4095)
        self.motor6value_dial.setObjectName(_fromUtf8("motor6value_dial"))
        self.horizontalLayout_9.addWidget(self.motor6value_dial)
        self.motor6Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor6Set_pushButton.setObjectName(_fromUtf8("motor6Set_pushButton"))
        self.horizontalLayout_9.addWidget(self.motor6Set_pushButton)
        self.motor6Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor6Get_pushButton.setObjectName(_fromUtf8("motor6Get_pushButton"))
        self.horizontalLayout_9.addWidget(self.motor6Get_pushButton)
        self.motor6DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor6DisT_pushButton.setObjectName(_fromUtf8("motor6DisT_pushButton"))
        self.horizontalLayout_9.addWidget(self.motor6DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.ID7_label = QtGui.QLabel(self.layoutWidget1)
        self.ID7_label.setObjectName(_fromUtf8("ID7_label"))
        self.horizontalLayout_10.addWidget(self.ID7_label)
        self.motorType7_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType7_label.setObjectName(_fromUtf8("motorType7_label"))
        self.horizontalLayout_10.addWidget(self.motorType7_label)
        self.motor7center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor7center_label.setObjectName(_fromUtf8("motor7center_label"))
        self.horizontalLayout_10.addWidget(self.motor7center_label)
        self.motor7Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor7Value_spinBox.setMaximum(4095)
        self.motor7Value_spinBox.setObjectName(_fromUtf8("motor7Value_spinBox"))
        self.horizontalLayout_10.addWidget(self.motor7Value_spinBox)
        self.motor7value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor7value_dial.setMaximum(4095)
        self.motor7value_dial.setObjectName(_fromUtf8("motor7value_dial"))
        self.horizontalLayout_10.addWidget(self.motor7value_dial)
        self.motor7Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor7Set_pushButton.setObjectName(_fromUtf8("motor7Set_pushButton"))
        self.horizontalLayout_10.addWidget(self.motor7Set_pushButton)
        self.motor7Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor7Get_pushButton.setObjectName(_fromUtf8("motor7Get_pushButton"))
        self.horizontalLayout_10.addWidget(self.motor7Get_pushButton)
        self.motor7DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor7DisT_pushButton.setObjectName(_fromUtf8("motor7DisT_pushButton"))
        self.horizontalLayout_10.addWidget(self.motor7DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.loadFile_pushButton = QtGui.QPushButton(Form)
        self.loadFile_pushButton.setGeometry(QtCore.QRect(1040, 40, 75, 23))
        self.loadFile_pushButton.setObjectName(_fromUtf8("loadFile_pushButton"))
        self.saveFile_pushButton = QtGui.QPushButton(Form)
        self.saveFile_pushButton.setGeometry(QtCore.QRect(1040, 10, 75, 23))
        self.saveFile_pushButton.setObjectName(_fromUtf8("saveFile_pushButton"))
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 531, 201))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.file_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.file_label.setObjectName(_fromUtf8("file_label"))
        self.horizontalLayout.addWidget(self.file_label)
        self.fileName_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.fileName_label.setObjectName(_fromUtf8("fileName_label"))
        self.horizontalLayout.addWidget(self.fileName_label)
        self.numOfKeyframe_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.numOfKeyframe_label.setObjectName(_fromUtf8("numOfKeyframe_label"))
        self.horizontalLayout.addWidget(self.numOfKeyframe_label)
        self.numOfKeyframeStatus_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.numOfKeyframeStatus_label.setObjectName(_fromUtf8("numOfKeyframeStatus_label"))
        self.horizontalLayout.addWidget(self.numOfKeyframeStatus_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.play_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.play_label.setObjectName(_fromUtf8("play_label"))
        self.horizontalLayout_27.addWidget(self.play_label)
        self.allKeyframe_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.allKeyframe_label.setObjectName(_fromUtf8("allKeyframe_label"))
        self.horizontalLayout_27.addWidget(self.allKeyframe_label)
        self.setReady_Button = QtGui.QPushButton(self.verticalLayoutWidget)
        self.setReady_Button.setObjectName(_fromUtf8("setReady_Button"))
        self.horizontalLayout_27.addWidget(self.setReady_Button)
        self.playAll_Button = QtGui.QPushButton(self.verticalLayoutWidget)
        self.playAll_Button.setObjectName(_fromUtf8("playAll_Button"))
        self.horizontalLayout_27.addWidget(self.playAll_Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.deleteKeyframe_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.deleteKeyframe_pushButton.setObjectName(_fromUtf8("deleteKeyframe_pushButton"))
        self.horizontalLayout_18.addWidget(self.deleteKeyframe_pushButton)
        self.duplicateKeyframe_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.duplicateKeyframe_pushButton.setObjectName(_fromUtf8("duplicateKeyframe_pushButton"))
        self.horizontalLayout_18.addWidget(self.duplicateKeyframe_pushButton)
        self.previousSwitchKeyframe_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.previousSwitchKeyframe_pushButton.setObjectName(_fromUtf8("previousSwitchKeyframe_pushButton"))
        self.horizontalLayout_18.addWidget(self.previousSwitchKeyframe_pushButton)
        self.nextSwitchKeyframe_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.nextSwitchKeyframe_pushButton.setObjectName(_fromUtf8("nextSwitchKeyframe_pushButton"))
        self.horizontalLayout_18.addWidget(self.nextSwitchKeyframe_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.SelectedKeyframe_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.SelectedKeyframe_label.setObjectName(_fromUtf8("SelectedKeyframe_label"))
        self.horizontalLayout_2.addWidget(self.SelectedKeyframe_label)
        self.keyFrame_comboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.keyFrame_comboBox.setObjectName(_fromUtf8("keyFrame_comboBox"))
        self.horizontalLayout_2.addWidget(self.keyFrame_comboBox)
        self.activeKeyframe_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.activeKeyframe_checkBox.setEnabled(True)
        self.activeKeyframe_checkBox.setObjectName(_fromUtf8("activeKeyframe_checkBox"))
        self.horizontalLayout_2.addWidget(self.activeKeyframe_checkBox)
        self.play_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.play_pushButton.setObjectName(_fromUtf8("play_pushButton"))
        self.horizontalLayout_2.addWidget(self.play_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.keyframeTime_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.keyframeTime_label.setObjectName(_fromUtf8("keyframeTime_label"))
        self.horizontalLayout_3.addWidget(self.keyframeTime_label)
        self.keyframeTime_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.keyframeTime_spinBox.setObjectName(_fromUtf8("keyframeTime_spinBox"))
        self.horizontalLayout_3.addWidget(self.keyframeTime_spinBox)
        self.setTime_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.setTime_pushButton.setObjectName(_fromUtf8("setTime_pushButton"))
        self.horizontalLayout_3.addWidget(self.setTime_pushButton)
        self.setAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.setAll_pushButton.setObjectName(_fromUtf8("setAll_pushButton"))
        self.horizontalLayout_3.addWidget(self.setAll_pushButton)
        self.getAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.getAll_pushButton.setObjectName(_fromUtf8("getAll_pushButton"))
        self.horizontalLayout_3.addWidget(self.getAll_pushButton)
        self.disTAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.disTAll_pushButton.setObjectName(_fromUtf8("disTAll_pushButton"))
        self.horizontalLayout_3.addWidget(self.disTAll_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 981, 51))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.postureName_label = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.postureName_label.setObjectName(_fromUtf8("postureName_label"))
        self.horizontalLayout_23.addWidget(self.postureName_label)
        self.posture_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.posture_comboBox.setObjectName(_fromUtf8("posture_comboBox"))
        self.horizontalLayout_23.addWidget(self.posture_comboBox)
        self.posture_number_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.posture_number_comboBox.setObjectName(_fromUtf8("posture_number_comboBox"))
        self.horizontalLayout_23.addWidget(self.posture_number_comboBox)
        self.loadPosture_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.loadPosture_pushButton.setObjectName(_fromUtf8("loadPosture_pushButton"))
        self.horizontalLayout_23.addWidget(self.loadPosture_pushButton)
        self.savePosture_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.savePosture_pushButton.setObjectName(_fromUtf8("savePosture_pushButton"))
        self.horizontalLayout_23.addWidget(self.savePosture_pushButton)
        self.saveCenter_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.saveCenter_pushButton.setObjectName(_fromUtf8("saveCenter_pushButton"))
        self.horizontalLayout_23.addWidget(self.saveCenter_pushButton)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.comport_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.comport_comboBox.setObjectName(_fromUtf8("comport_comboBox"))
        self.horizontalLayout_24.addWidget(self.comport_comboBox)
        self.baudrate_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.baudrate_comboBox.setObjectName(_fromUtf8("baudrate_comboBox"))
        self.horizontalLayout_24.addWidget(self.baudrate_comboBox)
        self.connectionStatus_label = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.connectionStatus_label.setObjectName(_fromUtf8("connectionStatus_label"))
        self.horizontalLayout_24.addWidget(self.connectionStatus_label)
        self.connect_Button = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.connect_Button.setObjectName(_fromUtf8("connect_Button"))
        self.horizontalLayout_24.addWidget(self.connect_Button)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_24)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.motor1value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor1Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor1Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor1value_dial.setValue)
        QtCore.QObject.connect(self.motor2value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor2Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor2Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor2value_dial.setValue)
        QtCore.QObject.connect(self.motor3value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor3Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor3Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor3value_dial.setValue)
        QtCore.QObject.connect(self.motor4value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor4Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor4Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor4value_dial.setValue)
        QtCore.QObject.connect(self.motor5value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor5Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor5Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor5value_dial.setValue)
        QtCore.QObject.connect(self.motor6value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor6Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor6Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor6value_dial.setValue)
        QtCore.QObject.connect(self.motor7value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor7Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor7Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor7value_dial.setValue)
        QtCore.QObject.connect(self.motor17value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor17Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor17Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor17value_dial.setValue)
        QtCore.QObject.connect(self.motor11value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor11Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor11Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor11value_dial.setValue)
        QtCore.QObject.connect(self.motor12value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor12Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor12Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor12value_dial.setValue)
        QtCore.QObject.connect(self.motor13value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor13Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor13Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor13value_dial.setValue)
        QtCore.QObject.connect(self.motor14value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor14Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor14Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor14value_dial.setValue)
        QtCore.QObject.connect(self.motor15value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor15Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor15Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor15value_dial.setValue)
        QtCore.QObject.connect(self.motor16value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor16Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor16Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor16value_dial.setValue)
        QtCore.QObject.connect(self.motor23value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor23Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor23Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor23value_dial.setValue)
        QtCore.QObject.connect(self.motor21value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor21Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor21Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor21value_dial.setValue)
        QtCore.QObject.connect(self.motor22value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor22Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor22Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor22value_dial.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.setHAll_pushButton.setText(_translate("Form", "Set H All", None))
        self.getHAll_pushButton.setText(_translate("Form", "Get H All", None))
        self.disTHAll_pushButton.setText(_translate("Form", "DisT H All", None))
        self.ID21_label.setText(_translate("Form", "ID21", None))
        self.motorType21_label.setText(_translate("Form", "RX", None))
        self.motor21center_label.setText(_translate("Form", "1023", None))
        self.motor21Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor21Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor21DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID22_label.setText(_translate("Form", "ID22", None))
        self.motorType22_label.setText(_translate("Form", "RX", None))
        self.motor22center_label.setText(_translate("Form", "1023", None))
        self.motor22Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor22Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor22DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID23_label.setText(_translate("Form", "ID23", None))
        self.motorType23_label.setText(_translate("Form", "RX", None))
        self.motor23center_label.setText(_translate("Form", "1023", None))
        self.motor23Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor23Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor23DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.setRAll_pushButton.setText(_translate("Form", "Set R All", None))
        self.getRAll_pushButton.setText(_translate("Form", "Get R All", None))
        self.disTRAll_pushButton.setText(_translate("Form", "DisT R All", None))
        self.ID11_label.setText(_translate("Form", "ID11", None))
        self.motorType11_label.setText(_translate("Form", "MX", None))
        self.motor11center_label.setText(_translate("Form", "2048", None))
        self.motor11Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor11Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor11DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID12_label.setText(_translate("Form", "ID12", None))
        self.motorType12_label.setText(_translate("Form", "MX", None))
        self.motor12center_label.setText(_translate("Form", "2048", None))
        self.motor12Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor12Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor12DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID13_label.setText(_translate("Form", "ID13", None))
        self.motorType13_label.setText(_translate("Form", "MX", None))
        self.motor13center_label.setText(_translate("Form", "2048", None))
        self.motor13Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor13Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor13DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID14_label.setText(_translate("Form", "ID14", None))
        self.motorType14_label.setText(_translate("Form", "MX", None))
        self.motor14center_label.setText(_translate("Form", "2048", None))
        self.motor14Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor14Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor14DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID15_label.setText(_translate("Form", "ID15", None))
        self.motorType15_label.setText(_translate("Form", "MX", None))
        self.motor15center_label.setText(_translate("Form", "2048", None))
        self.motor15Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor15Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor15DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID7_label_.setText(_translate("Form", "ID16", None))
        self.motorType16_label.setText(_translate("Form", "MX", None))
        self.motor16center_label.setText(_translate("Form", "2048", None))
        self.motor16Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor16Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor16DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID17_label.setText(_translate("Form", "ID17", None))
        self.motorType17_label.setText(_translate("Form", "MX", None))
        self.motor17center_label.setText(_translate("Form", "2048", None))
        self.motor17Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor17Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor17DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.setLAll_pushButton.setText(_translate("Form", "Set L All", None))
        self.getLAll_pushButton.setText(_translate("Form", "Get L All", None))
        self.disTLAll_pushButton.setText(_translate("Form", "DisT L All", None))
        self.ID1_label.setText(_translate("Form", "ID1", None))
        self.motorType1_label.setText(_translate("Form", "MX", None))
        self.motor1center_label.setText(_translate("Form", "2048", None))
        self.motor1Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor1Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor1DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID2_label.setText(_translate("Form", "ID2", None))
        self.motorType2_label.setText(_translate("Form", "MX", None))
        self.motor2center_label.setText(_translate("Form", "2048", None))
        self.motor2Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor2Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor2DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID3_label.setText(_translate("Form", "ID3", None))
        self.motorType3_label.setText(_translate("Form", "MX", None))
        self.motor3center_label.setText(_translate("Form", "2048", None))
        self.motor3Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor3Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor3DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID4_label.setText(_translate("Form", "ID4", None))
        self.motorType4_label.setText(_translate("Form", "MX", None))
        self.motor4center_label.setText(_translate("Form", "2048", None))
        self.motor4Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor4Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor4DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID5_label.setText(_translate("Form", "ID5", None))
        self.motorType5_label.setText(_translate("Form", "MX", None))
        self.motor5center_label.setText(_translate("Form", "2048", None))
        self.motor5Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor5Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor5DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID6_label.setText(_translate("Form", "ID6", None))
        self.motorType6_label.setText(_translate("Form", "MX", None))
        self.motor6center_label.setText(_translate("Form", "2048", None))
        self.motor6Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor6Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor6DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID7_label.setText(_translate("Form", "ID7", None))
        self.motorType7_label.setText(_translate("Form", "MX", None))
        self.motor7center_label.setText(_translate("Form", "2048", None))
        self.motor7Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor7Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor7DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.loadFile_pushButton.setText(_translate("Form", "Load File", None))
        self.saveFile_pushButton.setText(_translate("Form", "Save File", None))
        self.file_label.setText(_translate("Form", "File::", None))
        self.fileName_label.setText(_translate("Form", "File Name", None))
        self.numOfKeyframe_label.setText(_translate("Form", "Number of Keyframe", None))
        self.numOfKeyframeStatus_label.setText(_translate("Form", "0", None))
        self.play_label.setText(_translate("Form", "Play", None))
        self.allKeyframe_label.setText(_translate("Form", "All Keyframe", None))
        self.setReady_Button.setText(_translate("Form", "Set Ready", None))
        self.playAll_Button.setText(_translate("Form", "Play All", None))
        self.deleteKeyframe_pushButton.setText(_translate("Form", "Delete", None))
        self.duplicateKeyframe_pushButton.setText(_translate("Form", "Duplicate", None))
        self.previousSwitchKeyframe_pushButton.setText(_translate("Form", "Previous Switch", None))
        self.nextSwitchKeyframe_pushButton.setText(_translate("Form", "Next Switch", None))
        self.SelectedKeyframe_label.setText(_translate("Form", "Selected Keyframe", None))
        self.activeKeyframe_checkBox.setText(_translate("Form", "Active Keyframe", None))
        self.play_pushButton.setText(_translate("Form", "Play", None))
        self.keyframeTime_label.setText(_translate("Form", "KF Time =", None))
        self.setTime_pushButton.setText(_translate("Form", "Set Time", None))
        self.setAll_pushButton.setText(_translate("Form", "Set All", None))
        self.getAll_pushButton.setText(_translate("Form", "Get All", None))
        self.disTAll_pushButton.setText(_translate("Form", "DisT All", None))
        self.postureName_label.setText(_translate("Form", "Posture Name", None))
        self.loadPosture_pushButton.setText(_translate("Form", "Load", None))
        self.savePosture_pushButton.setText(_translate("Form", "Save", None))
        self.saveCenter_pushButton.setText(_translate("Form", "Save Center", None))
        self.connectionStatus_label.setText(_translate("Form", "connection Status", None))
        self.connect_Button.setText(_translate("Form", "Connect", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

