# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetPostureNamoUI_QT5.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1089, 759)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(550, 70, 531, 205))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.setHAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.setHAll_pushButton.setObjectName("setHAll_pushButton")
        self.horizontalLayout_26.addWidget(self.setHAll_pushButton)
        self.getHAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.getHAll_pushButton.setObjectName("getHAll_pushButton")
        self.horizontalLayout_26.addWidget(self.getHAll_pushButton)
        self.disTHAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.disTHAll_pushButton.setObjectName("disTHAll_pushButton")
        self.horizontalLayout_26.addWidget(self.disTHAll_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.ID21_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.ID21_label.setObjectName("ID21_label")
        self.horizontalLayout_20.addWidget(self.ID21_label)
        self.motorType21_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motorType21_label.setObjectName("motorType21_label")
        self.horizontalLayout_20.addWidget(self.motorType21_label)
        self.motor21center_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motor21center_label.setObjectName("motor21center_label")
        self.horizontalLayout_20.addWidget(self.motor21center_label)
        self.motor21Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.motor21Value_spinBox.setMaximum(1023)
        self.motor21Value_spinBox.setObjectName("motor21Value_spinBox")
        self.horizontalLayout_20.addWidget(self.motor21Value_spinBox)
        self.motor21value_dial = QtWidgets.QDial(self.verticalLayoutWidget_7)
        self.motor21value_dial.setMaximum(1023)
        self.motor21value_dial.setObjectName("motor21value_dial")
        self.horizontalLayout_20.addWidget(self.motor21value_dial)
        self.motor21Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor21Set_pushButton.setObjectName("motor21Set_pushButton")
        self.horizontalLayout_20.addWidget(self.motor21Set_pushButton)
        self.motor21Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor21Get_pushButton.setObjectName("motor21Get_pushButton")
        self.horizontalLayout_20.addWidget(self.motor21Get_pushButton)
        self.motor21DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor21DisT_pushButton.setObjectName("motor21DisT_pushButton")
        self.horizontalLayout_20.addWidget(self.motor21DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.ID22_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.ID22_label.setObjectName("ID22_label")
        self.horizontalLayout_21.addWidget(self.ID22_label)
        self.motorType22_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motorType22_label.setObjectName("motorType22_label")
        self.horizontalLayout_21.addWidget(self.motorType22_label)
        self.motor22center_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motor22center_label.setObjectName("motor22center_label")
        self.horizontalLayout_21.addWidget(self.motor22center_label)
        self.motor22Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.motor22Value_spinBox.setMaximum(1023)
        self.motor22Value_spinBox.setObjectName("motor22Value_spinBox")
        self.horizontalLayout_21.addWidget(self.motor22Value_spinBox)
        self.motor22value_dial = QtWidgets.QDial(self.verticalLayoutWidget_7)
        self.motor22value_dial.setMaximum(1023)
        self.motor22value_dial.setObjectName("motor22value_dial")
        self.horizontalLayout_21.addWidget(self.motor22value_dial)
        self.motor22Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor22Set_pushButton.setObjectName("motor22Set_pushButton")
        self.horizontalLayout_21.addWidget(self.motor22Set_pushButton)
        self.motor22Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor22Get_pushButton.setObjectName("motor22Get_pushButton")
        self.horizontalLayout_21.addWidget(self.motor22Get_pushButton)
        self.motor22DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor22DisT_pushButton.setObjectName("motor22DisT_pushButton")
        self.horizontalLayout_21.addWidget(self.motor22DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.ID23_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.ID23_label.setObjectName("ID23_label")
        self.horizontalLayout_19.addWidget(self.ID23_label)
        self.motorType23_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motorType23_label.setObjectName("motorType23_label")
        self.horizontalLayout_19.addWidget(self.motorType23_label)
        self.motor23center_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motor23center_label.setObjectName("motor23center_label")
        self.horizontalLayout_19.addWidget(self.motor23center_label)
        self.motor23Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.motor23Value_spinBox.setMaximum(1023)
        self.motor23Value_spinBox.setObjectName("motor23Value_spinBox")
        self.horizontalLayout_19.addWidget(self.motor23Value_spinBox)
        self.motor23value_dial = QtWidgets.QDial(self.verticalLayoutWidget_7)
        self.motor23value_dial.setMaximum(1023)
        self.motor23value_dial.setObjectName("motor23value_dial")
        self.horizontalLayout_19.addWidget(self.motor23value_dial)
        self.motor23Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor23Set_pushButton.setObjectName("motor23Set_pushButton")
        self.horizontalLayout_19.addWidget(self.motor23Set_pushButton)
        self.motor23Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor23Get_pushButton.setObjectName("motor23Get_pushButton")
        self.horizontalLayout_19.addWidget(self.motor23Get_pushButton)
        self.motor23DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor23DisT_pushButton.setObjectName("motor23DisT_pushButton")
        self.horizontalLayout_19.addWidget(self.motor23DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(550, 300, 531, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.setRAll_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.setRAll_pushButton.setObjectName("setRAll_pushButton")
        self.horizontalLayout_25.addWidget(self.setRAll_pushButton)
        self.getRAll_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.getRAll_pushButton.setObjectName("getRAll_pushButton")
        self.horizontalLayout_25.addWidget(self.getRAll_pushButton)
        self.disTRAll_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.disTRAll_pushButton.setObjectName("disTRAll_pushButton")
        self.horizontalLayout_25.addWidget(self.disTRAll_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ID11_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID11_label.setObjectName("ID11_label")
        self.horizontalLayout_12.addWidget(self.ID11_label)
        self.motorType11_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType11_label.setObjectName("motorType11_label")
        self.horizontalLayout_12.addWidget(self.motorType11_label)
        self.motor11center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor11center_label.setObjectName("motor11center_label")
        self.horizontalLayout_12.addWidget(self.motor11center_label)
        self.motor11Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor11Value_spinBox.setMaximum(4095)
        self.motor11Value_spinBox.setObjectName("motor11Value_spinBox")
        self.horizontalLayout_12.addWidget(self.motor11Value_spinBox)
        self.motor11value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor11value_dial.setMaximum(4095)
        self.motor11value_dial.setObjectName("motor11value_dial")
        self.horizontalLayout_12.addWidget(self.motor11value_dial)
        self.motor11Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor11Set_pushButton.setObjectName("motor11Set_pushButton")
        self.horizontalLayout_12.addWidget(self.motor11Set_pushButton)
        self.motor11Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor11Get_pushButton.setObjectName("motor11Get_pushButton")
        self.horizontalLayout_12.addWidget(self.motor11Get_pushButton)
        self.motor11DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor11DisT_pushButton.setObjectName("motor11DisT_pushButton")
        self.horizontalLayout_12.addWidget(self.motor11DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ID12_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID12_label.setObjectName("ID12_label")
        self.horizontalLayout_13.addWidget(self.ID12_label)
        self.motorType12_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType12_label.setObjectName("motorType12_label")
        self.horizontalLayout_13.addWidget(self.motorType12_label)
        self.motor12center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor12center_label.setObjectName("motor12center_label")
        self.horizontalLayout_13.addWidget(self.motor12center_label)
        self.motor12Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor12Value_spinBox.setMaximum(4095)
        self.motor12Value_spinBox.setObjectName("motor12Value_spinBox")
        self.horizontalLayout_13.addWidget(self.motor12Value_spinBox)
        self.motor12value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor12value_dial.setMaximum(4095)
        self.motor12value_dial.setObjectName("motor12value_dial")
        self.horizontalLayout_13.addWidget(self.motor12value_dial)
        self.motor12Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor12Set_pushButton.setObjectName("motor12Set_pushButton")
        self.horizontalLayout_13.addWidget(self.motor12Set_pushButton)
        self.motor12Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor12Get_pushButton.setObjectName("motor12Get_pushButton")
        self.horizontalLayout_13.addWidget(self.motor12Get_pushButton)
        self.motor12DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor12DisT_pushButton.setObjectName("motor12DisT_pushButton")
        self.horizontalLayout_13.addWidget(self.motor12DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ID13_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID13_label.setObjectName("ID13_label")
        self.horizontalLayout_14.addWidget(self.ID13_label)
        self.motorType13_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType13_label.setObjectName("motorType13_label")
        self.horizontalLayout_14.addWidget(self.motorType13_label)
        self.motor13center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor13center_label.setObjectName("motor13center_label")
        self.horizontalLayout_14.addWidget(self.motor13center_label)
        self.motor13Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor13Value_spinBox.setMaximum(4095)
        self.motor13Value_spinBox.setObjectName("motor13Value_spinBox")
        self.horizontalLayout_14.addWidget(self.motor13Value_spinBox)
        self.motor13value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor13value_dial.setMaximum(4095)
        self.motor13value_dial.setObjectName("motor13value_dial")
        self.horizontalLayout_14.addWidget(self.motor13value_dial)
        self.motor13Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor13Set_pushButton.setObjectName("motor13Set_pushButton")
        self.horizontalLayout_14.addWidget(self.motor13Set_pushButton)
        self.motor13Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor13Get_pushButton.setObjectName("motor13Get_pushButton")
        self.horizontalLayout_14.addWidget(self.motor13Get_pushButton)
        self.motor13DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor13DisT_pushButton.setObjectName("motor13DisT_pushButton")
        self.horizontalLayout_14.addWidget(self.motor13DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.ID14_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID14_label.setObjectName("ID14_label")
        self.horizontalLayout_15.addWidget(self.ID14_label)
        self.motorType14_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType14_label.setObjectName("motorType14_label")
        self.horizontalLayout_15.addWidget(self.motorType14_label)
        self.motor14center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor14center_label.setObjectName("motor14center_label")
        self.horizontalLayout_15.addWidget(self.motor14center_label)
        self.motor14Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor14Value_spinBox.setMaximum(4095)
        self.motor14Value_spinBox.setObjectName("motor14Value_spinBox")
        self.horizontalLayout_15.addWidget(self.motor14Value_spinBox)
        self.motor14value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor14value_dial.setMaximum(4095)
        self.motor14value_dial.setObjectName("motor14value_dial")
        self.horizontalLayout_15.addWidget(self.motor14value_dial)
        self.motor14Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor14Set_pushButton.setObjectName("motor14Set_pushButton")
        self.horizontalLayout_15.addWidget(self.motor14Set_pushButton)
        self.motor14Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor14Get_pushButton.setObjectName("motor14Get_pushButton")
        self.horizontalLayout_15.addWidget(self.motor14Get_pushButton)
        self.motor14DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor14DisT_pushButton.setObjectName("motor14DisT_pushButton")
        self.horizontalLayout_15.addWidget(self.motor14DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ID15_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID15_label.setObjectName("ID15_label")
        self.horizontalLayout_16.addWidget(self.ID15_label)
        self.motorType15_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType15_label.setObjectName("motorType15_label")
        self.horizontalLayout_16.addWidget(self.motorType15_label)
        self.motor15center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor15center_label.setObjectName("motor15center_label")
        self.horizontalLayout_16.addWidget(self.motor15center_label)
        self.motor15Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor15Value_spinBox.setMaximum(4095)
        self.motor15Value_spinBox.setObjectName("motor15Value_spinBox")
        self.horizontalLayout_16.addWidget(self.motor15Value_spinBox)
        self.motor15value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor15value_dial.setMaximum(4095)
        self.motor15value_dial.setObjectName("motor15value_dial")
        self.horizontalLayout_16.addWidget(self.motor15value_dial)
        self.motor15Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor15Set_pushButton.setObjectName("motor15Set_pushButton")
        self.horizontalLayout_16.addWidget(self.motor15Set_pushButton)
        self.motor15Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor15Get_pushButton.setObjectName("motor15Get_pushButton")
        self.horizontalLayout_16.addWidget(self.motor15Get_pushButton)
        self.motor15DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor15DisT_pushButton.setObjectName("motor15DisT_pushButton")
        self.horizontalLayout_16.addWidget(self.motor15DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ID7_label_ = QtWidgets.QLabel(self.layoutWidget)
        self.ID7_label_.setObjectName("ID7_label_")
        self.horizontalLayout_17.addWidget(self.ID7_label_)
        self.motorType16_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType16_label.setObjectName("motorType16_label")
        self.horizontalLayout_17.addWidget(self.motorType16_label)
        self.motor16center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor16center_label.setObjectName("motor16center_label")
        self.horizontalLayout_17.addWidget(self.motor16center_label)
        self.motor16Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor16Value_spinBox.setMaximum(4095)
        self.motor16Value_spinBox.setObjectName("motor16Value_spinBox")
        self.horizontalLayout_17.addWidget(self.motor16Value_spinBox)
        self.motor16value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor16value_dial.setMaximum(4095)
        self.motor16value_dial.setObjectName("motor16value_dial")
        self.horizontalLayout_17.addWidget(self.motor16value_dial)
        self.motor16Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor16Set_pushButton.setObjectName("motor16Set_pushButton")
        self.horizontalLayout_17.addWidget(self.motor16Set_pushButton)
        self.motor16Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor16Get_pushButton.setObjectName("motor16Get_pushButton")
        self.horizontalLayout_17.addWidget(self.motor16Get_pushButton)
        self.motor16DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor16DisT_pushButton.setObjectName("motor16DisT_pushButton")
        self.horizontalLayout_17.addWidget(self.motor16DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ID17_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID17_label.setObjectName("ID17_label")
        self.horizontalLayout_11.addWidget(self.ID17_label)
        self.motorType17_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType17_label.setObjectName("motorType17_label")
        self.horizontalLayout_11.addWidget(self.motorType17_label)
        self.motor17center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor17center_label.setObjectName("motor17center_label")
        self.horizontalLayout_11.addWidget(self.motor17center_label)
        self.motor17Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor17Value_spinBox.setMaximum(4095)
        self.motor17Value_spinBox.setObjectName("motor17Value_spinBox")
        self.horizontalLayout_11.addWidget(self.motor17Value_spinBox)
        self.motor17value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor17value_dial.setMaximum(4095)
        self.motor17value_dial.setObjectName("motor17value_dial")
        self.horizontalLayout_11.addWidget(self.motor17value_dial)
        self.motor17Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor17Set_pushButton.setObjectName("motor17Set_pushButton")
        self.horizontalLayout_11.addWidget(self.motor17Set_pushButton)
        self.motor17Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor17Get_pushButton.setObjectName("motor17Get_pushButton")
        self.horizontalLayout_11.addWidget(self.motor17Get_pushButton)
        self.motor17DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor17DisT_pushButton.setObjectName("motor17DisT_pushButton")
        self.horizontalLayout_11.addWidget(self.motor17DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 300, 531, 451))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.setLAll_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.setLAll_pushButton.setObjectName("setLAll_pushButton")
        self.horizontalLayout_22.addWidget(self.setLAll_pushButton)
        self.getLAll_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.getLAll_pushButton.setObjectName("getLAll_pushButton")
        self.horizontalLayout_22.addWidget(self.getLAll_pushButton)
        self.disTLAll_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.disTLAll_pushButton.setObjectName("disTLAll_pushButton")
        self.horizontalLayout_22.addWidget(self.disTLAll_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ID1_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID1_label.setObjectName("ID1_label")
        self.horizontalLayout_4.addWidget(self.ID1_label)
        self.motorType1_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType1_label.setObjectName("motorType1_label")
        self.horizontalLayout_4.addWidget(self.motorType1_label)
        self.motor1center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor1center_label.setObjectName("motor1center_label")
        self.horizontalLayout_4.addWidget(self.motor1center_label)
        self.motor1Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor1Value_spinBox.setMaximum(4095)
        self.motor1Value_spinBox.setObjectName("motor1Value_spinBox")
        self.horizontalLayout_4.addWidget(self.motor1Value_spinBox)
        self.motor1value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor1value_dial.setMaximum(4095)
        self.motor1value_dial.setObjectName("motor1value_dial")
        self.horizontalLayout_4.addWidget(self.motor1value_dial)
        self.motor1Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor1Set_pushButton.setObjectName("motor1Set_pushButton")
        self.horizontalLayout_4.addWidget(self.motor1Set_pushButton)
        self.motor1Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor1Get_pushButton.setObjectName("motor1Get_pushButton")
        self.horizontalLayout_4.addWidget(self.motor1Get_pushButton)
        self.motor1DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor1DisT_pushButton.setObjectName("motor1DisT_pushButton")
        self.horizontalLayout_4.addWidget(self.motor1DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ID2_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID2_label.setObjectName("ID2_label")
        self.horizontalLayout_5.addWidget(self.ID2_label)
        self.motorType2_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType2_label.setObjectName("motorType2_label")
        self.horizontalLayout_5.addWidget(self.motorType2_label)
        self.motor2center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor2center_label.setObjectName("motor2center_label")
        self.horizontalLayout_5.addWidget(self.motor2center_label)
        self.motor2Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor2Value_spinBox.setMaximum(4095)
        self.motor2Value_spinBox.setObjectName("motor2Value_spinBox")
        self.horizontalLayout_5.addWidget(self.motor2Value_spinBox)
        self.motor2value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor2value_dial.setMaximum(4095)
        self.motor2value_dial.setObjectName("motor2value_dial")
        self.horizontalLayout_5.addWidget(self.motor2value_dial)
        self.motor2Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor2Set_pushButton.setObjectName("motor2Set_pushButton")
        self.horizontalLayout_5.addWidget(self.motor2Set_pushButton)
        self.motor2Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor2Get_pushButton.setObjectName("motor2Get_pushButton")
        self.horizontalLayout_5.addWidget(self.motor2Get_pushButton)
        self.motor2DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor2DisT_pushButton.setObjectName("motor2DisT_pushButton")
        self.horizontalLayout_5.addWidget(self.motor2DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ID3_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID3_label.setObjectName("ID3_label")
        self.horizontalLayout_6.addWidget(self.ID3_label)
        self.motorType3_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType3_label.setObjectName("motorType3_label")
        self.horizontalLayout_6.addWidget(self.motorType3_label)
        self.motor3center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor3center_label.setObjectName("motor3center_label")
        self.horizontalLayout_6.addWidget(self.motor3center_label)
        self.motor3Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor3Value_spinBox.setMaximum(4095)
        self.motor3Value_spinBox.setObjectName("motor3Value_spinBox")
        self.horizontalLayout_6.addWidget(self.motor3Value_spinBox)
        self.motor3value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor3value_dial.setMaximum(4095)
        self.motor3value_dial.setObjectName("motor3value_dial")
        self.horizontalLayout_6.addWidget(self.motor3value_dial)
        self.motor3Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor3Set_pushButton.setObjectName("motor3Set_pushButton")
        self.horizontalLayout_6.addWidget(self.motor3Set_pushButton)
        self.motor3Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor3Get_pushButton.setObjectName("motor3Get_pushButton")
        self.horizontalLayout_6.addWidget(self.motor3Get_pushButton)
        self.motor3DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor3DisT_pushButton.setObjectName("motor3DisT_pushButton")
        self.horizontalLayout_6.addWidget(self.motor3DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ID4_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID4_label.setObjectName("ID4_label")
        self.horizontalLayout_7.addWidget(self.ID4_label)
        self.motorType4_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType4_label.setObjectName("motorType4_label")
        self.horizontalLayout_7.addWidget(self.motorType4_label)
        self.motor4center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor4center_label.setObjectName("motor4center_label")
        self.horizontalLayout_7.addWidget(self.motor4center_label)
        self.motor4Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor4Value_spinBox.setMaximum(4095)
        self.motor4Value_spinBox.setObjectName("motor4Value_spinBox")
        self.horizontalLayout_7.addWidget(self.motor4Value_spinBox)
        self.motor4value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor4value_dial.setMaximum(4095)
        self.motor4value_dial.setObjectName("motor4value_dial")
        self.horizontalLayout_7.addWidget(self.motor4value_dial)
        self.motor4Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor4Set_pushButton.setObjectName("motor4Set_pushButton")
        self.horizontalLayout_7.addWidget(self.motor4Set_pushButton)
        self.motor4Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor4Get_pushButton.setObjectName("motor4Get_pushButton")
        self.horizontalLayout_7.addWidget(self.motor4Get_pushButton)
        self.motor4DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor4DisT_pushButton.setObjectName("motor4DisT_pushButton")
        self.horizontalLayout_7.addWidget(self.motor4DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ID5_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID5_label.setObjectName("ID5_label")
        self.horizontalLayout_8.addWidget(self.ID5_label)
        self.motorType5_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType5_label.setObjectName("motorType5_label")
        self.horizontalLayout_8.addWidget(self.motorType5_label)
        self.motor5center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor5center_label.setObjectName("motor5center_label")
        self.horizontalLayout_8.addWidget(self.motor5center_label)
        self.motor5Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor5Value_spinBox.setMaximum(4095)
        self.motor5Value_spinBox.setObjectName("motor5Value_spinBox")
        self.horizontalLayout_8.addWidget(self.motor5Value_spinBox)
        self.motor5value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor5value_dial.setMaximum(4095)
        self.motor5value_dial.setObjectName("motor5value_dial")
        self.horizontalLayout_8.addWidget(self.motor5value_dial)
        self.motor5Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor5Set_pushButton.setObjectName("motor5Set_pushButton")
        self.horizontalLayout_8.addWidget(self.motor5Set_pushButton)
        self.motor5Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor5Get_pushButton.setObjectName("motor5Get_pushButton")
        self.horizontalLayout_8.addWidget(self.motor5Get_pushButton)
        self.motor5DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor5DisT_pushButton.setObjectName("motor5DisT_pushButton")
        self.horizontalLayout_8.addWidget(self.motor5DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ID6_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID6_label.setObjectName("ID6_label")
        self.horizontalLayout_9.addWidget(self.ID6_label)
        self.motorType6_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType6_label.setObjectName("motorType6_label")
        self.horizontalLayout_9.addWidget(self.motorType6_label)
        self.motor6center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor6center_label.setObjectName("motor6center_label")
        self.horizontalLayout_9.addWidget(self.motor6center_label)
        self.motor6Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor6Value_spinBox.setMaximum(4095)
        self.motor6Value_spinBox.setObjectName("motor6Value_spinBox")
        self.horizontalLayout_9.addWidget(self.motor6Value_spinBox)
        self.motor6value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor6value_dial.setMaximum(4095)
        self.motor6value_dial.setObjectName("motor6value_dial")
        self.horizontalLayout_9.addWidget(self.motor6value_dial)
        self.motor6Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor6Set_pushButton.setObjectName("motor6Set_pushButton")
        self.horizontalLayout_9.addWidget(self.motor6Set_pushButton)
        self.motor6Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor6Get_pushButton.setObjectName("motor6Get_pushButton")
        self.horizontalLayout_9.addWidget(self.motor6Get_pushButton)
        self.motor6DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor6DisT_pushButton.setObjectName("motor6DisT_pushButton")
        self.horizontalLayout_9.addWidget(self.motor6DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ID7_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID7_label.setObjectName("ID7_label")
        self.horizontalLayout_10.addWidget(self.ID7_label)
        self.motorType7_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType7_label.setObjectName("motorType7_label")
        self.horizontalLayout_10.addWidget(self.motorType7_label)
        self.motor7center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor7center_label.setObjectName("motor7center_label")
        self.horizontalLayout_10.addWidget(self.motor7center_label)
        self.motor7Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor7Value_spinBox.setMaximum(4095)
        self.motor7Value_spinBox.setObjectName("motor7Value_spinBox")
        self.horizontalLayout_10.addWidget(self.motor7Value_spinBox)
        self.motor7value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor7value_dial.setMaximum(4095)
        self.motor7value_dial.setObjectName("motor7value_dial")
        self.horizontalLayout_10.addWidget(self.motor7value_dial)
        self.motor7Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor7Set_pushButton.setObjectName("motor7Set_pushButton")
        self.horizontalLayout_10.addWidget(self.motor7Set_pushButton)
        self.motor7Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor7Get_pushButton.setObjectName("motor7Get_pushButton")
        self.horizontalLayout_10.addWidget(self.motor7Get_pushButton)
        self.motor7DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor7DisT_pushButton.setObjectName("motor7DisT_pushButton")
        self.horizontalLayout_10.addWidget(self.motor7DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.loadFile_pushButton = QtWidgets.QPushButton(Form)
        self.loadFile_pushButton.setGeometry(QtCore.QRect(1000, 40, 75, 23))
        self.loadFile_pushButton.setObjectName("loadFile_pushButton")
        self.saveFile_pushButton = QtWidgets.QPushButton(Form)
        self.saveFile_pushButton.setGeometry(QtCore.QRect(1000, 10, 75, 23))
        self.saveFile_pushButton.setObjectName("saveFile_pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 531, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.file_label.setObjectName("file_label")
        self.horizontalLayout.addWidget(self.file_label)
        self.fileName_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fileName_label.setObjectName("fileName_label")
        self.horizontalLayout.addWidget(self.fileName_label)
        self.numOfKeyframe_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.numOfKeyframe_label.setObjectName("numOfKeyframe_label")
        self.horizontalLayout.addWidget(self.numOfKeyframe_label)
        self.numOfKeyframeStatus_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.numOfKeyframeStatus_label.setObjectName("numOfKeyframeStatus_label")
        self.horizontalLayout.addWidget(self.numOfKeyframeStatus_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.play_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.play_label.setObjectName("play_label")
        self.horizontalLayout_27.addWidget(self.play_label)
        self.allKeyframe_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.allKeyframe_label.setObjectName("allKeyframe_label")
        self.horizontalLayout_27.addWidget(self.allKeyframe_label)
        self.setReady_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.setReady_Button.setObjectName("setReady_Button")
        self.horizontalLayout_27.addWidget(self.setReady_Button)
        self.playAll_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.playAll_Button.setObjectName("playAll_Button")
        self.horizontalLayout_27.addWidget(self.playAll_Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.deleteKeyframe_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deleteKeyframe_pushButton.setObjectName("deleteKeyframe_pushButton")
        self.horizontalLayout_18.addWidget(self.deleteKeyframe_pushButton)
        self.duplicateKeyframe_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.duplicateKeyframe_pushButton.setObjectName("duplicateKeyframe_pushButton")
        self.horizontalLayout_18.addWidget(self.duplicateKeyframe_pushButton)
        self.previousSwitchKeyframe_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.previousSwitchKeyframe_pushButton.setObjectName("previousSwitchKeyframe_pushButton")
        self.horizontalLayout_18.addWidget(self.previousSwitchKeyframe_pushButton)
        self.nextSwitchKeyframe_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nextSwitchKeyframe_pushButton.setObjectName("nextSwitchKeyframe_pushButton")
        self.horizontalLayout_18.addWidget(self.nextSwitchKeyframe_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SelectedKeyframe_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.SelectedKeyframe_label.setObjectName("SelectedKeyframe_label")
        self.horizontalLayout_2.addWidget(self.SelectedKeyframe_label)
        self.keyFrame_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.keyFrame_comboBox.setObjectName("keyFrame_comboBox")
        self.horizontalLayout_2.addWidget(self.keyFrame_comboBox)
        self.activeKeyframe_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.activeKeyframe_checkBox.setEnabled(True)
        self.activeKeyframe_checkBox.setObjectName("activeKeyframe_checkBox")
        self.horizontalLayout_2.addWidget(self.activeKeyframe_checkBox)
        self.play_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.play_pushButton.setObjectName("play_pushButton")
        self.horizontalLayout_2.addWidget(self.play_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.keyframeTime_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.keyframeTime_label.setObjectName("keyframeTime_label")
        self.horizontalLayout_3.addWidget(self.keyframeTime_label)
        self.keyframeTime_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.keyframeTime_spinBox.setObjectName("keyframeTime_spinBox")
        self.horizontalLayout_3.addWidget(self.keyframeTime_spinBox)
        self.setTime_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.setTime_pushButton.setObjectName("setTime_pushButton")
        self.horizontalLayout_3.addWidget(self.setTime_pushButton)
        self.setAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.setAll_pushButton.setObjectName("setAll_pushButton")
        self.horizontalLayout_3.addWidget(self.setAll_pushButton)
        self.getAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.getAll_pushButton.setObjectName("getAll_pushButton")
        self.horizontalLayout_3.addWidget(self.getAll_pushButton)
        self.disTAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.disTAll_pushButton.setObjectName("disTAll_pushButton")
        self.horizontalLayout_3.addWidget(self.disTAll_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 921, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.postureName_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.postureName_label.setObjectName("postureName_label")
        self.horizontalLayout_23.addWidget(self.postureName_label)
        self.posture_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.posture_comboBox.setObjectName("posture_comboBox")
        self.horizontalLayout_23.addWidget(self.posture_comboBox)
        self.posture_number_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.posture_number_comboBox.setObjectName("posture_number_comboBox")
        self.horizontalLayout_23.addWidget(self.posture_number_comboBox)
        self.loadPosture_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.loadPosture_pushButton.setObjectName("loadPosture_pushButton")
        self.horizontalLayout_23.addWidget(self.loadPosture_pushButton)
        self.savePosture_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.savePosture_pushButton.setObjectName("savePosture_pushButton")
        self.horizontalLayout_23.addWidget(self.savePosture_pushButton)
        self.saveCenter_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.saveCenter_pushButton.setObjectName("saveCenter_pushButton")
        self.horizontalLayout_23.addWidget(self.saveCenter_pushButton)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.comport_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.comport_comboBox.setObjectName("comport_comboBox")
        self.horizontalLayout_24.addWidget(self.comport_comboBox)
        self.baudrate_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.baudrate_comboBox.setObjectName("baudrate_comboBox")
        self.horizontalLayout_24.addWidget(self.baudrate_comboBox)
        self.connectionStatus_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.connectionStatus_label.setObjectName("connectionStatus_label")
        self.horizontalLayout_24.addWidget(self.connectionStatus_label)
        self.connect_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.connect_Button.setObjectName("connect_Button")
        self.horizontalLayout_24.addWidget(self.connect_Button)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_24)
        self.gesture_type_groupBox = QtWidgets.QGroupBox(Form)
        self.gesture_type_groupBox.setGeometry(QtCore.QRect(10, 250, 531, 41))
        self.gesture_type_groupBox.setObjectName("gesture_type_groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gesture_type_groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 521, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.ready_gesture_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.ready_gesture_radioButton.setChecked(True)
        self.ready_gesture_radioButton.setObjectName("ready_gesture_radioButton")
        self.horizontalLayout_29.addWidget(self.ready_gesture_radioButton)
        self.pre_gesture_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.pre_gesture_radioButton.setObjectName("pre_gesture_radioButton")
        self.horizontalLayout_29.addWidget(self.pre_gesture_radioButton)
        self.main_gesture_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.main_gesture_radioButton.setObjectName("main_gesture_radioButton")
        self.horizontalLayout_29.addWidget(self.main_gesture_radioButton)
        self.pos_gesture_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.pos_gesture_radioButton.setObjectName("pos_gesture_radioButton")
        self.horizontalLayout_29.addWidget(self.pos_gesture_radioButton)

        self.retranslateUi(Form)
        self.motor1value_dial.valueChanged['int'].connect(self.motor1Value_spinBox.setValue)
        self.motor1Value_spinBox.valueChanged['int'].connect(self.motor1value_dial.setValue)
        self.motor2value_dial.valueChanged['int'].connect(self.motor2Value_spinBox.setValue)
        self.motor2Value_spinBox.valueChanged['int'].connect(self.motor2value_dial.setValue)
        self.motor3value_dial.valueChanged['int'].connect(self.motor3Value_spinBox.setValue)
        self.motor3Value_spinBox.valueChanged['int'].connect(self.motor3value_dial.setValue)
        self.motor4value_dial.valueChanged['int'].connect(self.motor4Value_spinBox.setValue)
        self.motor4Value_spinBox.valueChanged['int'].connect(self.motor4value_dial.setValue)
        self.motor5value_dial.valueChanged['int'].connect(self.motor5Value_spinBox.setValue)
        self.motor5Value_spinBox.valueChanged['int'].connect(self.motor5value_dial.setValue)
        self.motor6value_dial.valueChanged['int'].connect(self.motor6Value_spinBox.setValue)
        self.motor6Value_spinBox.valueChanged['int'].connect(self.motor6value_dial.setValue)
        self.motor7value_dial.valueChanged['int'].connect(self.motor7Value_spinBox.setValue)
        self.motor7Value_spinBox.valueChanged['int'].connect(self.motor7value_dial.setValue)
        self.motor17value_dial.valueChanged['int'].connect(self.motor17Value_spinBox.setValue)
        self.motor17Value_spinBox.valueChanged['int'].connect(self.motor17value_dial.setValue)
        self.motor11value_dial.valueChanged['int'].connect(self.motor11Value_spinBox.setValue)
        self.motor11Value_spinBox.valueChanged['int'].connect(self.motor11value_dial.setValue)
        self.motor12value_dial.valueChanged['int'].connect(self.motor12Value_spinBox.setValue)
        self.motor12Value_spinBox.valueChanged['int'].connect(self.motor12value_dial.setValue)
        self.motor13value_dial.valueChanged['int'].connect(self.motor13Value_spinBox.setValue)
        self.motor13Value_spinBox.valueChanged['int'].connect(self.motor13value_dial.setValue)
        self.motor14value_dial.valueChanged['int'].connect(self.motor14Value_spinBox.setValue)
        self.motor14Value_spinBox.valueChanged['int'].connect(self.motor14value_dial.setValue)
        self.motor15value_dial.valueChanged['int'].connect(self.motor15Value_spinBox.setValue)
        self.motor15Value_spinBox.valueChanged['int'].connect(self.motor15value_dial.setValue)
        self.motor16value_dial.valueChanged['int'].connect(self.motor16Value_spinBox.setValue)
        self.motor16Value_spinBox.valueChanged['int'].connect(self.motor16value_dial.setValue)
        self.motor23value_dial.valueChanged['int'].connect(self.motor23Value_spinBox.setValue)
        self.motor23Value_spinBox.valueChanged['int'].connect(self.motor23value_dial.setValue)
        self.motor21value_dial.valueChanged['int'].connect(self.motor21Value_spinBox.setValue)
        self.motor21Value_spinBox.valueChanged['int'].connect(self.motor21value_dial.setValue)
        self.motor22value_dial.valueChanged['int'].connect(self.motor22Value_spinBox.setValue)
        self.motor22Value_spinBox.valueChanged['int'].connect(self.motor22value_dial.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.setHAll_pushButton.setText(_translate("Form", "Set H All"))
        self.getHAll_pushButton.setText(_translate("Form", "Get H All"))
        self.disTHAll_pushButton.setText(_translate("Form", "DisT H All"))
        self.ID21_label.setText(_translate("Form", "ID21"))
        self.motorType21_label.setText(_translate("Form", "RX"))
        self.motor21center_label.setText(_translate("Form", "1023"))
        self.motor21Set_pushButton.setText(_translate("Form", "Set"))
        self.motor21Get_pushButton.setText(_translate("Form", "Get"))
        self.motor21DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID22_label.setText(_translate("Form", "ID22"))
        self.motorType22_label.setText(_translate("Form", "RX"))
        self.motor22center_label.setText(_translate("Form", "1023"))
        self.motor22Set_pushButton.setText(_translate("Form", "Set"))
        self.motor22Get_pushButton.setText(_translate("Form", "Get"))
        self.motor22DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID23_label.setText(_translate("Form", "ID23"))
        self.motorType23_label.setText(_translate("Form", "RX"))
        self.motor23center_label.setText(_translate("Form", "1023"))
        self.motor23Set_pushButton.setText(_translate("Form", "Set"))
        self.motor23Get_pushButton.setText(_translate("Form", "Get"))
        self.motor23DisT_pushButton.setText(_translate("Form", "DisT"))
        self.setRAll_pushButton.setText(_translate("Form", "Set R All"))
        self.getRAll_pushButton.setText(_translate("Form", "Get R All"))
        self.disTRAll_pushButton.setText(_translate("Form", "DisT R All"))
        self.ID11_label.setText(_translate("Form", "ID11"))
        self.motorType11_label.setText(_translate("Form", "MX"))
        self.motor11center_label.setText(_translate("Form", "2048"))
        self.motor11Set_pushButton.setText(_translate("Form", "Set"))
        self.motor11Get_pushButton.setText(_translate("Form", "Get"))
        self.motor11DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID12_label.setText(_translate("Form", "ID12"))
        self.motorType12_label.setText(_translate("Form", "MX"))
        self.motor12center_label.setText(_translate("Form", "2048"))
        self.motor12Set_pushButton.setText(_translate("Form", "Set"))
        self.motor12Get_pushButton.setText(_translate("Form", "Get"))
        self.motor12DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID13_label.setText(_translate("Form", "ID13"))
        self.motorType13_label.setText(_translate("Form", "MX"))
        self.motor13center_label.setText(_translate("Form", "2048"))
        self.motor13Set_pushButton.setText(_translate("Form", "Set"))
        self.motor13Get_pushButton.setText(_translate("Form", "Get"))
        self.motor13DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID14_label.setText(_translate("Form", "ID14"))
        self.motorType14_label.setText(_translate("Form", "MX"))
        self.motor14center_label.setText(_translate("Form", "2048"))
        self.motor14Set_pushButton.setText(_translate("Form", "Set"))
        self.motor14Get_pushButton.setText(_translate("Form", "Get"))
        self.motor14DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID15_label.setText(_translate("Form", "ID15"))
        self.motorType15_label.setText(_translate("Form", "MX"))
        self.motor15center_label.setText(_translate("Form", "2048"))
        self.motor15Set_pushButton.setText(_translate("Form", "Set"))
        self.motor15Get_pushButton.setText(_translate("Form", "Get"))
        self.motor15DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID7_label_.setText(_translate("Form", "ID16"))
        self.motorType16_label.setText(_translate("Form", "MX"))
        self.motor16center_label.setText(_translate("Form", "2048"))
        self.motor16Set_pushButton.setText(_translate("Form", "Set"))
        self.motor16Get_pushButton.setText(_translate("Form", "Get"))
        self.motor16DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID17_label.setText(_translate("Form", "ID17"))
        self.motorType17_label.setText(_translate("Form", "MX"))
        self.motor17center_label.setText(_translate("Form", "2048"))
        self.motor17Set_pushButton.setText(_translate("Form", "Set"))
        self.motor17Get_pushButton.setText(_translate("Form", "Get"))
        self.motor17DisT_pushButton.setText(_translate("Form", "DisT"))
        self.setLAll_pushButton.setText(_translate("Form", "Set L All"))
        self.getLAll_pushButton.setText(_translate("Form", "Get L All"))
        self.disTLAll_pushButton.setText(_translate("Form", "DisT L All"))
        self.ID1_label.setText(_translate("Form", "ID1"))
        self.motorType1_label.setText(_translate("Form", "MX"))
        self.motor1center_label.setText(_translate("Form", "2048"))
        self.motor1Set_pushButton.setText(_translate("Form", "Set"))
        self.motor1Get_pushButton.setText(_translate("Form", "Get"))
        self.motor1DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID2_label.setText(_translate("Form", "ID2"))
        self.motorType2_label.setText(_translate("Form", "MX"))
        self.motor2center_label.setText(_translate("Form", "2048"))
        self.motor2Set_pushButton.setText(_translate("Form", "Set"))
        self.motor2Get_pushButton.setText(_translate("Form", "Get"))
        self.motor2DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID3_label.setText(_translate("Form", "ID3"))
        self.motorType3_label.setText(_translate("Form", "MX"))
        self.motor3center_label.setText(_translate("Form", "2048"))
        self.motor3Set_pushButton.setText(_translate("Form", "Set"))
        self.motor3Get_pushButton.setText(_translate("Form", "Get"))
        self.motor3DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID4_label.setText(_translate("Form", "ID4"))
        self.motorType4_label.setText(_translate("Form", "MX"))
        self.motor4center_label.setText(_translate("Form", "2048"))
        self.motor4Set_pushButton.setText(_translate("Form", "Set"))
        self.motor4Get_pushButton.setText(_translate("Form", "Get"))
        self.motor4DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID5_label.setText(_translate("Form", "ID5"))
        self.motorType5_label.setText(_translate("Form", "MX"))
        self.motor5center_label.setText(_translate("Form", "2048"))
        self.motor5Set_pushButton.setText(_translate("Form", "Set"))
        self.motor5Get_pushButton.setText(_translate("Form", "Get"))
        self.motor5DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID6_label.setText(_translate("Form", "ID6"))
        self.motorType6_label.setText(_translate("Form", "MX"))
        self.motor6center_label.setText(_translate("Form", "2048"))
        self.motor6Set_pushButton.setText(_translate("Form", "Set"))
        self.motor6Get_pushButton.setText(_translate("Form", "Get"))
        self.motor6DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID7_label.setText(_translate("Form", "ID7"))
        self.motorType7_label.setText(_translate("Form", "MX"))
        self.motor7center_label.setText(_translate("Form", "2048"))
        self.motor7Set_pushButton.setText(_translate("Form", "Set"))
        self.motor7Get_pushButton.setText(_translate("Form", "Get"))
        self.motor7DisT_pushButton.setText(_translate("Form", "DisT"))
        self.loadFile_pushButton.setText(_translate("Form", "Load File"))
        self.saveFile_pushButton.setText(_translate("Form", "Save File"))
        self.file_label.setText(_translate("Form", "File::"))
        self.fileName_label.setText(_translate("Form", "File Name"))
        self.numOfKeyframe_label.setText(_translate("Form", "Number of Keyframe"))
        self.numOfKeyframeStatus_label.setText(_translate("Form", "0"))
        self.play_label.setText(_translate("Form", "Play"))
        self.allKeyframe_label.setText(_translate("Form", "All Keyframe"))
        self.setReady_Button.setText(_translate("Form", "Set Ready"))
        self.playAll_Button.setText(_translate("Form", "Play All"))
        self.deleteKeyframe_pushButton.setText(_translate("Form", "Delete"))
        self.duplicateKeyframe_pushButton.setText(_translate("Form", "Duplicate"))
        self.previousSwitchKeyframe_pushButton.setText(_translate("Form", "Previous Switch"))
        self.nextSwitchKeyframe_pushButton.setText(_translate("Form", "Next Switch"))
        self.SelectedKeyframe_label.setText(_translate("Form", "Selected Keyframe"))
        self.activeKeyframe_checkBox.setText(_translate("Form", "Active Keyframe"))
        self.play_pushButton.setText(_translate("Form", "Play"))
        self.keyframeTime_label.setText(_translate("Form", "KF Time ="))
        self.setTime_pushButton.setText(_translate("Form", "Set Time"))
        self.setAll_pushButton.setText(_translate("Form", "Set All"))
        self.getAll_pushButton.setText(_translate("Form", "Get All"))
        self.disTAll_pushButton.setText(_translate("Form", "DisT All"))
        self.postureName_label.setText(_translate("Form", "Posture Name"))
        self.loadPosture_pushButton.setText(_translate("Form", "Load"))
        self.savePosture_pushButton.setText(_translate("Form", "Save"))
        self.saveCenter_pushButton.setText(_translate("Form", "Save Center"))
        self.connectionStatus_label.setText(_translate("Form", "connection Status"))
        self.connect_Button.setText(_translate("Form", "Connect"))
        self.gesture_type_groupBox.setTitle(_translate("Form", "Gesture Type"))
        self.ready_gesture_radioButton.setText(_translate("Form", "Ready Gesture"))
        self.pre_gesture_radioButton.setText(_translate("Form", "Pre Gesture"))
        self.main_gesture_radioButton.setText(_translate("Form", "Main Gesture"))
        self.pos_gesture_radioButton.setText(_translate("Form", "Pos Gesture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

